name: "Build curriculum PDF"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Render CV
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Render CV
        run: |
          python -m pip install --upgrade pip
          pip install "rendercv[full]"
      - name: Render Curriculum PDF
        run: |
          rendercv render Mateus_Navarro_CV.yaml
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mateus_Navarro_CV_PT.pdf
          path: rendercv_output/Mateus_Navarro_CV_PT.pdf